pipeline {
    agent any

    stages {
        stage('Build and Push Docker Image') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'kapila2511', variable: 'DOCKER_HUB_PASSWORD')]) {
                        // Log in to Docker Hub securely using the Jenkins credentials
                        sh "docker login -u kapila25 -p \$DOCKER_HUB_PASSWORD"

                        // Build and push the Docker image
                        docker.build("kapila25/front:61").push()
                    }
                }
            }
        }

        // The rest of your pipeline stages
    }
}
